# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecommand',
            name='access_level',
        ),
    ]
