# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-04 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_gateway_default_color'),
        ('processor', '0003_servicecommand_gateway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecommand',
            name='gateway',
        ),
        migrations.AddField(
            model_name='servicecommand',
            name='gateway',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway'),
            preserve_default=False,
        ),
    ]
