# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='refererhost',
            name='page',
        ),
        migrations.AddField(
            model_name='refererhost',
            name='permissions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gui.Permission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='access_level',
            field=models.ManyToManyField(blank=True, to='administration.AccessLevel'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='gateway',
            field=models.ManyToManyField(blank=True, to='administration.Gateway'),
        ),
        migrations.AlterField(
            model_name='refererhost',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.PermissionStatus'),
        ),
        migrations.DeleteModel(
            name='RefererHostStatus',
        ),
    ]
