# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='template',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='gui.Template'),
            preserve_default=False,
        ),
    ]
