# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_pages_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='service',
            field=models.CharField(default='HOME', max_length=200),
            preserve_default=False,
        ),
    ]
