# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_pages_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='path',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
