# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_auto_20160812_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='access_level',
        ),
    ]
