# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-31 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_gateway_default_color'),
        ('gui', '0007_remove_permission_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Pages')),
            ],
        ),
        migrations.CreateModel(
            name='InitialPageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='initialpage',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.InitialPageStatus'),
        ),
    ]
