# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-04 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_gateway_default_color'),
        ('gui', '0010_initialpage_subdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialpage',
            name='gateway',
        ),
        migrations.AddField(
            model_name='initialpage',
            name='gateway',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway'),
            preserve_default=False,
        ),
    ]
